# Stub Makefile for Modules (add2lib only)
CC = $(DEVKITPPC)/bin/powerpc-eabi-gcc
OPT = -g -O2 -Wall -Wstrict-prototypes -fPIC -Os -Wall -msoft-float
CFLAGS = $(OPT) -I../Include -I.. -DHAVE_CONFIG_H
AR = $(DEVKITPPC)/bin/powerpc-eabi-ar
RANLIB = $(DEVKITPPC)/bin/powerpc-eabi-ranlib

all:

add2lib:
	echo libmodules.a >> ../add2lib

clean:
