# Stub Makefile for Modules (add2lib only)
CC = /opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc
OPT = -g -O2 -Wall -Wstrict-prototypes -fPIC -Os -Wall -msoft-float
CFLAGS = $(OPT) -I../Include -I.. -DHAVE_CONFIG_H
AR = /opt/devkitpro/devkitPPC/bin/powerpc-eabi-ar
RANLIB = /opt/devkitpro/devkitPPC/bin/powerpc-eabi-ranlib

all:

add2lib:
	echo libmodules.a >> ../add2lib

clean:
