/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t test1[];
extern const uint8_t test1_end[];
#if __cplusplus >= 201103L
static constexpr size_t test1_size=1;
#else
static const size_t test1_size=1;
#endif
