
/* Frozen modules initializer
 *
 * Frozen modules are written to header files by Programs/_freeze_module.
 * These files are typically put in Python/frozen_modules/.  Each holds
 * an array of bytes named "_Py_M__<module>", which is used below.
 *
 * These files must be regenerated any time the corresponding .pyc
 * file would change (including with changes to the compiler, bytecode
 * format, marshal format).  This can be done with "make regen-frozen".
 * That make target just runs Tools/build/freeze_modules.py.
 *
 * The freeze_modules.py script also determines which modules get
 * frozen.  Update the list at the top of the script to add, remove,
 * or modify the target modules.  Then run the script
 * (or run "make regen-frozen").
 *
 * The script does the following:
 *
 * 1. run Programs/_freeze_module on the target modules
 * 2. update the includes and _PyImport_FrozenModules[] in this file
 * 3. update the FROZEN_FILES variable in Makefile.pre.in
 * 4. update the per-module targets in Makefile.pre.in
 * 5. update the lists of modules in PCbuild/_freeze_module.vcxproj and
 *    PCbuild/_freeze_module.vcxproj.filters
 *
 * (Note that most of the data in this file is auto-generated by the script.)
 *
 * Those steps can also be done manually, though this is not recommended.
 * Expect such manual changes to be removed the next time
 * freeze_modules.py runs.
 * */

/* In order to test the support for frozen modules, by default we
   define some simple frozen modules: __hello__, __phello__ (a package),
   and __phello__.spam.  Loading any will print some famous words... */

#include "Python.h"
#include "pycore_import.h"

#include <stdbool.h>

/* Includes for frozen modules: */
#include "frozen_modules/importlib._bootstrap.h"
#include "frozen_modules/importlib._bootstrap_external.h"
#include "frozen_modules/zipimport.h"
#include "frozen_modules/abc.h"
#include "frozen_modules/codecs.h"
#include "frozen_modules/tokenize.h"
#include "frozen_modules/token.h"
#include "frozen_modules/re.h"
#include "frozen_modules/re._casefix.h"
#include "frozen_modules/re._compiler.h"
#include "frozen_modules/re._constants.h"
#include "frozen_modules/re._parser.h"
#include "frozen_modules/functools.h"
#include "frozen_modules/collections.h"
#include "frozen_modules/types.h"
#include "frozen_modules/traceback.h"
#include "frozen_modules/encodings.h"
#include "frozen_modules/encodings._win_cp_codecs.h"
#include "frozen_modules/encodings.aliases.h"
#include "frozen_modules/encodings.ascii.h"
#include "frozen_modules/encodings.base64_codec.h"
#include "frozen_modules/encodings.big5.h"
#include "frozen_modules/encodings.big5hkscs.h"
#include "frozen_modules/encodings.bz2_codec.h"
#include "frozen_modules/encodings.charmap.h"
#include "frozen_modules/encodings.cp037.h"
#include "frozen_modules/encodings.cp1006.h"
#include "frozen_modules/encodings.cp1026.h"
#include "frozen_modules/encodings.cp1125.h"
#include "frozen_modules/encodings.cp1140.h"
#include "frozen_modules/encodings.cp1250.h"
#include "frozen_modules/encodings.cp1251.h"
#include "frozen_modules/encodings.cp1252.h"
#include "frozen_modules/encodings.cp1253.h"
#include "frozen_modules/encodings.cp1254.h"
#include "frozen_modules/encodings.cp1255.h"
#include "frozen_modules/encodings.cp1256.h"
#include "frozen_modules/encodings.cp1257.h"
#include "frozen_modules/encodings.cp1258.h"
#include "frozen_modules/encodings.cp273.h"
#include "frozen_modules/encodings.cp424.h"
#include "frozen_modules/encodings.cp437.h"
#include "frozen_modules/encodings.cp500.h"
#include "frozen_modules/encodings.cp720.h"
#include "frozen_modules/encodings.cp737.h"
#include "frozen_modules/encodings.cp775.h"
#include "frozen_modules/encodings.cp850.h"
#include "frozen_modules/encodings.cp852.h"
#include "frozen_modules/encodings.cp855.h"
#include "frozen_modules/encodings.cp856.h"
#include "frozen_modules/encodings.cp857.h"
#include "frozen_modules/encodings.cp858.h"
#include "frozen_modules/encodings.cp860.h"
#include "frozen_modules/encodings.cp861.h"
#include "frozen_modules/encodings.cp862.h"
#include "frozen_modules/encodings.cp863.h"
#include "frozen_modules/encodings.cp864.h"
#include "frozen_modules/encodings.cp865.h"
#include "frozen_modules/encodings.cp866.h"
#include "frozen_modules/encodings.cp869.h"
#include "frozen_modules/encodings.cp874.h"
#include "frozen_modules/encodings.cp875.h"
#include "frozen_modules/encodings.cp932.h"
#include "frozen_modules/encodings.cp949.h"
#include "frozen_modules/encodings.cp950.h"
#include "frozen_modules/encodings.euc_jis_2004.h"
#include "frozen_modules/encodings.euc_jisx0213.h"
#include "frozen_modules/encodings.euc_jp.h"
#include "frozen_modules/encodings.euc_kr.h"
#include "frozen_modules/encodings.gb18030.h"
#include "frozen_modules/encodings.gb2312.h"
#include "frozen_modules/encodings.gbk.h"
#include "frozen_modules/encodings.hex_codec.h"
#include "frozen_modules/encodings.hp_roman8.h"
#include "frozen_modules/encodings.hz.h"
#include "frozen_modules/encodings.idna.h"
#include "frozen_modules/encodings.iso2022_jp.h"
#include "frozen_modules/encodings.iso2022_jp_1.h"
#include "frozen_modules/encodings.iso2022_jp_2.h"
#include "frozen_modules/encodings.iso2022_jp_2004.h"
#include "frozen_modules/encodings.iso2022_jp_3.h"
#include "frozen_modules/encodings.iso2022_jp_ext.h"
#include "frozen_modules/encodings.iso2022_kr.h"
#include "frozen_modules/encodings.iso8859_1.h"
#include "frozen_modules/encodings.iso8859_10.h"
#include "frozen_modules/encodings.iso8859_11.h"
#include "frozen_modules/encodings.iso8859_13.h"
#include "frozen_modules/encodings.iso8859_14.h"
#include "frozen_modules/encodings.iso8859_15.h"
#include "frozen_modules/encodings.iso8859_16.h"
#include "frozen_modules/encodings.iso8859_2.h"
#include "frozen_modules/encodings.iso8859_3.h"
#include "frozen_modules/encodings.iso8859_4.h"
#include "frozen_modules/encodings.iso8859_5.h"
#include "frozen_modules/encodings.iso8859_6.h"
#include "frozen_modules/encodings.iso8859_7.h"
#include "frozen_modules/encodings.iso8859_8.h"
#include "frozen_modules/encodings.iso8859_9.h"
#include "frozen_modules/encodings.johab.h"
#include "frozen_modules/encodings.koi8_r.h"
#include "frozen_modules/encodings.koi8_t.h"
#include "frozen_modules/encodings.koi8_u.h"
#include "frozen_modules/encodings.kz1048.h"
#include "frozen_modules/encodings.latin_1.h"
#include "frozen_modules/encodings.mac_arabic.h"
#include "frozen_modules/encodings.mac_croatian.h"
#include "frozen_modules/encodings.mac_cyrillic.h"
#include "frozen_modules/encodings.mac_farsi.h"
#include "frozen_modules/encodings.mac_greek.h"
#include "frozen_modules/encodings.mac_iceland.h"
#include "frozen_modules/encodings.mac_latin2.h"
#include "frozen_modules/encodings.mac_roman.h"
#include "frozen_modules/encodings.mac_romanian.h"
#include "frozen_modules/encodings.mac_turkish.h"
#include "frozen_modules/encodings.mbcs.h"
#include "frozen_modules/encodings.oem.h"
#include "frozen_modules/encodings.palmos.h"
#include "frozen_modules/encodings.ptcp154.h"
#include "frozen_modules/encodings.punycode.h"
#include "frozen_modules/encodings.quopri_codec.h"
#include "frozen_modules/encodings.raw_unicode_escape.h"
#include "frozen_modules/encodings.rot_13.h"
#include "frozen_modules/encodings.shift_jis.h"
#include "frozen_modules/encodings.shift_jis_2004.h"
#include "frozen_modules/encodings.shift_jisx0213.h"
#include "frozen_modules/encodings.tis_620.h"
#include "frozen_modules/encodings.undefined.h"
#include "frozen_modules/encodings.unicode_escape.h"
#include "frozen_modules/encodings.utf_16.h"
#include "frozen_modules/encodings.utf_16_be.h"
#include "frozen_modules/encodings.utf_16_le.h"
#include "frozen_modules/encodings.utf_32.h"
#include "frozen_modules/encodings.utf_32_be.h"
#include "frozen_modules/encodings.utf_32_le.h"
#include "frozen_modules/encodings.utf_7.h"
#include "frozen_modules/encodings.utf_8.h"
#include "frozen_modules/encodings.utf_8_sig.h"
#include "frozen_modules/encodings.uu_codec.h"
#include "frozen_modules/encodings.zlib_codec.h"
#include "frozen_modules/importlib.h"
#include "frozen_modules/importlib._abc.h"
#include "frozen_modules/importlib.abc.h"
#include "frozen_modules/importlib.machinery.h"
#include "frozen_modules/importlib.metadata.h"
#include "frozen_modules/importlib.readers.h"
#include "frozen_modules/importlib.resources.h"
#include "frozen_modules/importlib.simple.h"
#include "frozen_modules/importlib.util.h"
#include "frozen_modules/io.h"
#include "frozen_modules/_collections_abc.h"
#include "frozen_modules/_sitebuiltins.h"
#include "frozen_modules/genericpath.h"
#include "frozen_modules/ntpath.h"
#include "frozen_modules/posixpath.h"
#include "frozen_modules/os.h"
#include "frozen_modules/site.h"
#include "frozen_modules/stat.h"
#include "frozen_modules/runpy.h"
#ifdef WII_BUILD
#include "frozen_modules/pkgutil.h"
#endif
#ifdef WII_BUILD
#include "frozen_modules/enum.h"
#include "frozen_modules/keyword.h"
#include "frozen_modules/operator.h"
#include "frozen_modules/copyreg.h"
#include "frozen_modules/reprlib.h"
#include "frozen_modules/warnings.h"
#include "frozen_modules/_py_warnings.h"
#include "frozen_modules/threading.h"
#include "frozen_modules/weakref.h"
#include "frozen_modules/_weakrefset.h"
#include "frozen_modules/copy.h"
#include "frozen_modules/_compat_pickle.h"
#include "frozen_modules/xml.h"
#include "frozen_modules/xml.etree.h"
#include "frozen_modules/xml.etree.ElementPath.h"
#include "frozen_modules/sysconfig.h"
#include "frozen_modules/struct.h"
#include "frozen_modules/zoneinfo.h"
#include "frozen_modules/zoneinfo._tzpath.h"
#include "frozen_modules/zoneinfo._common.h"
#endif /* WII_BUILD */
#ifdef WII_BUILD
#include "frozen_modules/__hello__.h"
#include "frozen_modules/__phello__.h"
#include "frozen_modules/__phello__.ham.h"
#include "frozen_modules/__phello__.ham.eggs.h"
#include "frozen_modules/__phello__.spam.h"
#include "frozen_modules/frozen_only.h"
#endif /* WII_BUILD */
/* End includes */

static const struct _frozen bootstrap_modules[] = {
    {"_frozen_importlib", _Py_M__importlib__bootstrap, (int)sizeof(_Py_M__importlib__bootstrap), false},
    {"_frozen_importlib_external", _Py_M__importlib__bootstrap_external, (int)sizeof(_Py_M__importlib__bootstrap_external), false},
    {"zipimport", _Py_M__zipimport, (int)sizeof(_Py_M__zipimport), false},
    {"importlib._bootstrap", _Py_M__importlib__bootstrap, (int)sizeof(_Py_M__importlib__bootstrap), false},
    {"importlib._bootstrap_external", _Py_M__importlib__bootstrap_external, (int)sizeof(_Py_M__importlib__bootstrap_external), false},
    {0, 0, 0} /* bootstrap sentinel */
};
static const struct _frozen stdlib_modules[] = {
    /* stdlib - startup, without site (python -S) */
    {"abc", _Py_M__abc, (int)sizeof(_Py_M__abc), false},
    {"codecs", _Py_M__codecs, (int)sizeof(_Py_M__codecs), false},

    {"functools", _Py_M__functools, (int)sizeof(_Py_M__functools), false},
    {"collections", _Py_M__collections, (int)sizeof(_Py_M__collections), true},
    {"collections.__init__", _Py_M__collections, (int)sizeof(_Py_M__collections), false},
    {"types", _Py_M__types, (int)sizeof(_Py_M__types), false},
    {"traceback", _Py_M__traceback, (int)sizeof(_Py_M__traceback), false},
    {"encodings", _Py_M__encodings, (int)sizeof(_Py_M__encodings), true},

    {"encodings.aliases", _Py_M__encodings_aliases, (int)sizeof(_Py_M__encodings_aliases), false},
    {"encodings.ascii", _Py_M__encodings_ascii, (int)sizeof(_Py_M__encodings_ascii), false},

    {"encodings.latin_1", _Py_M__encodings_latin_1, (int)sizeof(_Py_M__encodings_latin_1), false},

    {"encodings.utf_8", _Py_M__encodings_utf_8, (int)sizeof(_Py_M__encodings_utf_8), false},

    {"importlib", _Py_M__importlib, (int)sizeof(_Py_M__importlib), true},

    {"importlib.machinery", _Py_M__importlib_machinery, (int)sizeof(_Py_M__importlib_machinery), false},

    {"importlib.util", _Py_M__importlib_util, (int)sizeof(_Py_M__importlib_util), false},
    {"importlib._abc", _Py_M__importlib__abc, (int)sizeof(_Py_M__importlib__abc), false},
    {"importlib.abc", _Py_M__importlib_abc, (int)sizeof(_Py_M__importlib_abc), false},
    {"importlib.metadata", _Py_M__importlib_metadata, (int)sizeof(_Py_M__importlib_metadata), true},
    {"importlib.readers", _Py_M__importlib_readers, (int)sizeof(_Py_M__importlib_readers), false},
    {"importlib.resources", _Py_M__importlib_resources, (int)sizeof(_Py_M__importlib_resources), true},
    {"importlib.simple", _Py_M__importlib_simple, (int)sizeof(_Py_M__importlib_simple), false},
    {"io", _Py_M__io, (int)sizeof(_Py_M__io), false},

    /* stdlib - startup, with site */
    {"_collections_abc", _Py_M___collections_abc, (int)sizeof(_Py_M___collections_abc), false},
    {"_sitebuiltins", _Py_M___sitebuiltins, (int)sizeof(_Py_M___sitebuiltins), false},
    {"genericpath", _Py_M__genericpath, (int)sizeof(_Py_M__genericpath), false},
    {"ntpath", _Py_M__ntpath, (int)sizeof(_Py_M__ntpath), false},
    {"posixpath", _Py_M__posixpath, (int)sizeof(_Py_M__posixpath), false},
    {"os", _Py_M__os, (int)sizeof(_Py_M__os), false},
    {"site", _Py_M__site, (int)sizeof(_Py_M__site), false},
    {"stat", _Py_M__stat, (int)sizeof(_Py_M__stat), false},

    /* runpy - run module with -m */
    {"runpy", _Py_M__runpy, (int)sizeof(_Py_M__runpy), false},
#ifdef WII_BUILD
    {"pkgutil", _Py_M__pkgutil, (int)sizeof(_Py_M__pkgutil), false},
#endif

    /* Wii extra frozen modules (keine .py-Dateien auf SD verfuegbar) */
#ifdef WII_BUILD
    {"warnings",        _Py_M__warnings,        (int)sizeof(_Py_M__warnings),        false},
    {"_py_warnings",    _Py_M___py_warnings,    (int)sizeof(_Py_M___py_warnings),    false},
#endif /* WII_BUILD */

    {0, 0, 0} /* stdlib sentinel */
};
static const struct _frozen test_modules[] = {
#ifdef WII_BUILD
    {"__hello__", _Py_M____hello__, (int)sizeof(_Py_M____hello__), false},
    {"__hello_alias__", _Py_M____hello__, (int)sizeof(_Py_M____hello__), false},

    {"__phello__", _Py_M____phello__, (int)sizeof(_Py_M____phello__), true},

    {"__phello__.ham", _Py_M____phello___ham, (int)sizeof(_Py_M____phello___ham), true},

    {"__phello__.spam", _Py_M____phello___spam, (int)sizeof(_Py_M____phello___spam), false},
#endif /* WII_BUILD */

    {0, 0, 0} /* test sentinel */
};
const struct _frozen *_PyImport_FrozenBootstrap = bootstrap_modules;
const struct _frozen *_PyImport_FrozenStdlib = stdlib_modules;
const struct _frozen *_PyImport_FrozenTest = test_modules;

static const struct _module_alias aliases[] = {
    {"_frozen_importlib", "importlib._bootstrap"},
    {"_frozen_importlib_external", "importlib._bootstrap_external"},

    {"collections.__init__", "<collections"},

    {"__hello_alias__", "__hello__"},

    {0, 0} /* aliases sentinel */
};
const struct _module_alias *_PyImport_FrozenAliases = aliases;

/* Embedding apps may change this pointer to point to their favorite
   collection of frozen modules: */

const struct _frozen *PyImport_FrozenModules = NULL;
